CREATE DATABASE DEMO
USE DEMO
CREATE TABLE NHANVIEN (
	MANV CHAR(9) CONSTRAINT PK_NHANVIEN PRIMARY KEY,
	HONV VARCHAR(10) NOT NULL,
	TENLOT VARCHAR(20) NOT NULL,
	TENNV VARCHAR(10) NOT NULL,
	NGSINH 	DATETIME ,
	DCHI VARCHAR(50),
	PHAI CHAR(3) check (PHAI IN ('Nam','Nu')),
	LUONG INT,
	MA_NQL CHAR(9),
	PHG INT
)
SELECT*FROM NHANVIEN
